### ISSUE TITLE
Setup Kanban Board - Review 

### ISSUE THREAD

**Issue by oluyaratosin123** [oluyaratosin123/Recipe-App-II#22]
In this issue, we:
- Added an automated kanban board
- Created issues that redirected to the kanban board
- Assigned the tasks equally to two different students:
- - @Thermiee - Student A
- - @oluyaratosin123  - Student B

Here is the link for the project https://github.com/oluyaratosin123/Recipe-App-II/projects/2

**Comment by Lordkaito** [comment]
Hi @oluyaratosin123, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
 - [ ] As requested by the previous reviewer, please add the tasks for `Show list of food that is missing for all recipes of the logged-in user` and `Count the total food items and total price of the missing food` as they are part of the requirements.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oluyaratosin123** [comment]
Hello @Lordkaito, Do you mean I should add the recent added issues to the project as a todo task?

**Comment by oluyaratosin123** [comment]
Here is the project todo:
![CaptureXXI](https://user-images.githubusercontent.com/83566118/174668506-604e7604-3e96-4663-add7-5925ac9551f9.PNG)

**Comment by Deepakdanger** [comment]
Hi @oluyaratosin123 & @Thermiee, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
